name: Build and deploy Node.js app to Azure Web App - hair-salon79

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./**  # Upload all files in the current directory and subdirectories
          retention-days: 1
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: false

      # Add a custom upload script for batching if needed
      # Uncomment the block below to use a custom upload script
      # - name: Upload artifacts in smaller batches
      #   run: |
      #     mkdir batches
      #     find . -type f | split -l 1000 - batches/batch_
      #     for batch in batches/batch_*; do
      #       echo "Uploading batch: $batch"
      #       actions/upload-artifact@v4
      #       with:
      #         name: node-app-batch-${{ github.run_id }}-${{ github.run.number }}-${{ matrix.index }}
      #         path: $(cat $batch)
      #     done

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: "hair-salon79"
          slot-name: "production"
          package: .  # Ensure the package path is correct after download
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_8420ae1cac8f4cc6a679cfff8fd2f3d4 }}
